export default {
  ADD_WORKOUT_EXERCISE: 'ADD_WORKOUT_EXERCISE',
  UPDATE_WORKOUT_EXERCISE: 'UPDATE_WORKOUT_EXERCISE',
  DELETE_WORKOUT_EXERCISE: 'DELETE_WORKOUT_EXERCISE',
  ADD_CURRENT_WORKOUT_EXERCISE: 'ADD_CURRENT_WORKOUT_EXERCISE',
  SET_CURRENT_WORKOUT_EXERCISE: 'SET_CURRENT_WORKOUT_EXERCISE',
  CLEAR_CURRENT_WORKOUT_EXERCISE: 'CLEAR_CURRENT_WORKOUT_EXERCISE',
  UPDATE_CURRENT_WORKOUT_EXERCISE: 'UPDATE_CURRENT_WORKOUT_EXERCISE',
  UPDATE_CURRENT_WORKOUT_EXERCISES: 'UPDATE_CURRENT_WORKOUT_EXERCISES',
  CLEAR_CURRENT_WORKOUT_EXERCISES: 'CLEAR_CURRENT_WORKOUT_EXERCISES',
  FETCH_WORKOUT_EXERCISES: 'FETCH_WORKOUT_EXERCISES',
  UPDATE_WORKOUT_EXERCISES: 'UPDATE_WORKOUT_EXERCISES',
  SET_WORKOUT_EXERCISES_ERROR: 'SET_WORKOUT_EXERCISES_ERROR',
};
