const types = {
  ADD_WORKOUT: 'ADD_WORKOUT',
  FETCH_ALL_WORKOUTS: 'FETCH_ALL_WORKOUTS',
  FETCH_NEXT_WORKOUT: 'FETCH_NEXT_WORKOUT',
  SET_NEXT_WORKOUT: 'SET_NEXT_WORKOUT',
  CLEAR_NEXT_WORKOUT: 'CLEAR_NEXT_WORKOUT',
};

export default types;
