const types = {
  ADD_WORKOUT: 'ADD_WORKOUT',
  SET_CURRENT_WORKOUT: 'SET_CURRENT_WORKOUT',
  UPDATE_CURRENT_WORKOUT: 'UPDATE_CURRENT_WORKOUT',
  DELETE_CURRENT_WORKOUT: 'DELETE_CURRENT_WORKOUT',
  CLEAR_CURRENT_WORKOUT: 'CLEAR_CURRENT_WORKOUT',
  FETCH_ALL_WORKOUTS: 'FETCH_ALL_WORKOUTS',
  SET_ALL_WORKOUTS: 'SET_ALL_WORKOUTS',
  UPDATE_ALL_WORKOUTS: 'UPDATE_ALL_WORKOUTS',
  CLEAR_ALL_WORKOUTS: 'CLEAR_ALL_WORKOUTS',
};

export default types;
