export default {
  ADD_EXERCISE: 'ADD_EXERCISE',
  UPDATE_EXERCISE: 'UPDATE_EXERCISE',
  ADD_CURRENT_EXERCISE: 'ADD_CURRENT_EXERCISE',
  SET_CURRENT_EXERCISE: 'SET_CURRENT_EXERCISE',
  UPDATE_CURRENT_EXERCISE: 'UPDATE_CURRENT_EXERCISE',
  CLEAR_CURRENT_EXERCISE: 'CLEAR_CURRENT_EXERCISE',
  FETCH_ALL_EXERCISES: 'FETCH_ALL_EXERCISES',
  CLEAR_ALL_EXERCISES: 'CLEAR_ALL_EXERCISES',
  RESET_EXERCISES: 'RESET_EXERCISES',
  SET_EXERCISES_ERROR: 'SET_EXERCISES_ERROR',
};
