const currentWorkoutTypes = {
  SET_CURRENT_WORKOUT: 'SET_CURRENT_WORKOUT',
  UPDATE_CURRENT_WORKOUT: 'UPDATE_CURRENT_WORKOUT',
  CLEAR_CURRENT_WORKOUT: 'CLEAR_CURRENT_WORKOUT',
};

export default currentWorkoutTypes;
