const currentExercise = {
  SET_CURRENT_EXERCISE: 'SET_CURRENT_EXERCISE',
  UPDATE_CURRENT_EXERCISE: 'UPDATE_CURRENT_EXERCISE',
  CLEAR_CURRENT_EXERCISE: 'CLEAR_CURRENT_EXERCISE',
};

export default currentExercise;
