const exerciseLogTypes = {
  ADD_EXERCISE_LOG: 'ADD_EXERCISE_LOG',
  UPDATE_EXERCISE_LOG: 'UPDATE_EXERCISE_LOG',
  GET_ACTIVE_EXERCISE_LOG: 'GET_ACTIVE_EXERCISE_LOG',
  SET_CURRENT_EXERCISE_LOGS: 'SET_CURRENT_EXERCISE_LOGS',
  CLEAR_CURRENT_EXERCISE_LOGS: 'CLEAR_CURRENT_EXERCISE_LOGS',
  SET_CURRENT_EXERCISE_LOG: 'SET_CURRENT_EXERCISE_LOG',
  SET_PREVIOUS_EXERCISE_LOG: 'SET_PREVIOUS_EXERCISE_LOG',
  UPDATE_CURRENT_EXERCISE_LOG: 'UPDATE_CURRENT_EXERCISE_LOG',
  CLEAR_CURRENT_EXERCISE_LOG: 'CLEAR_CURRENT_EXERCISE_LOG',
  RESET_EXERCISE_LOGS: 'RESET_EXERCISE_LOGS',
};

export default exerciseLogTypes;
