const programLogsTypes = {
  SET_CURRENT_PROGRAM_LOG: 'SET_CURRENT_PROGRAM_LOG',
  SET_PROGRAM_LOGS: 'SET_PROGRAM_LOGS',
  RESET_PROGRAM_LOGS: 'RESET_PROGRAM_LOGS',
};

export default programLogsTypes;
