const programLogsTypes = {
  GET_ACTIVE_PROGRAM_LOG: 'GET_ACTIVE_PROGRAM_LOG',
  CLEAR_ACTIVE_PROGRAM_LOG: 'CLEAR_ACTIVE_PROGRAM_LOG',
  SET_CURRENT_PROGRAM_LOG: 'SET_CURRENT_PROGRAM_LOG',
  UPDATE_CURRENT_PROGRAM_LOG: 'UPDATE_CURRENT_PROGRAM_LOG',
  UPDATE_PROGRAM_LOG: 'UPDATE_PROGRAM_LOG',
  FETCH_PROGRAM_LOGS: 'FETCH_PROGRAM_LOGS',
  SET_PROGRAM_LOGS: 'SET_PROGRAM_LOGS',
  RESET_PROGRAM_LOGS: 'RESET_PROGRAM_LOGS',
  ABANDON_PROGRAM_LOG: 'ABANDON_PROGRAM_LOG',
  CLEAR_ACTIVE_PROGRAM_LOG: 'CLEAR_ACTIVE_PROGRAM_LOG',
};

export default programLogsTypes;
