const currentWorkoutsTypes = {
  SET_CURRENT_WORKOUTS: 'SET_CURRENT_WORKOUTS',
  ADD_CURRENT_WORKOUT: 'ADD_CURRENT_WORKOUT',
  UPDATE_CURRENT_WORKOUTS: 'UPDATE_CURRENT_WORKOUTS',
  UPDATE_CURRENT_WORKOUT: 'UPDATE_CURRENT_WORKOUT',
  DELETE_CURRENT_WORKOUT: 'DELETE_CURRENT_WORKOUT',
  CLEAR_CURRENT_WORKOUTS: 'CLEAR_CURRENT_WORKOUTS',
};

export default currentWorkoutsTypes;
