const types = {
  ADD_WORKOUT_LOG: 'ADD_WORKOUT_LOG',
  UPDATE_WORKOUT_LOG: 'UPDATE_WORKOUT_LOG',
  SET_WORKOUT_LOGS: 'SET_WORKOUT_LOGS',
  GET_ACTIVE_WORKOUT_LOG: 'GET_ACTIVE_WORKOUT_LOG',
  CLEAR_ACTIVE_WORKOUT_LOG: 'CLEAR_ACTIVE_WORKOUT_LOG',
  SET_CURRENT_WORKOUT_LOG: 'SET_CURRENT_WORKOUT_LOG',
  CLEAR_CURRENT_WORKOUT_LOG: 'CLEAR_CURRENT_WORKOUT_LOG',
  SKIP_WORKOUT_LOG: 'SKIP_WORKOUT_LOG',
  RESET_WORKOUT_LOGS: 'RESET_WORKOUT_LOGS',
};

export default types;
