export default {
  ADD_PROGRAM: 'ADD_PROGRAM',
  FETCH_PROGRAMS: 'FETCH_PROGRAMS',
  CLEAR_PROGRAMS: 'CLEAR_PROGRAMS',
  SET_CURRENT_PROGRAM: 'SET_CURRENT_PROGRAM',
  UPDATE_CURRENT_PROGRAM: 'UPDATE_CURRENT_PROGRAM',
  CLEAR_CURRENT_PROGRAM: 'CLEAR_CURRENT_PROGRAM',
  RESET_PROGRAMS: 'RESET_PROGRAMS',
  SET_PROGRAMS_ERROR: 'SET_PROGRAMS_ERROR',
};
