const currentExercises = {
  SET_CURRENT_EXERCISES: 'SET_CURRENT_EXERCISES',
  UPDATE_CURRENT_EXERCISES: 'UPDATE_CURRENT_EXERCISES',
  UPDATE_ONE_CURRENT_EXERCISES: 'UPDATE_ONE_CURRENT_EXERCISES',
  CLEAR_CURRENT_EXERCISES: 'CLEAR_CURRENT_EXERCISES',
};

export default currentExercises;
