const types = {
  FETCH_PROGRAM_WORKOUTS: 'FETCH_PROGRAM_WORKOUTS',
  SET_PROGRAM_WORKOUTS: 'SET_PROGRAM_WORKOUTS',
  CLEAR_CURRENT_PROGRAM_WORKOUTS: 'CLEAR_CURRENT_PROGRAM_WORKOUTS',
  UPDATE_PROGRAM_WORKOUT: 'UPDATE_PROGRAM_WORKOUT',
  UPDATE_PROGRAM_WORKOUTS: 'UPDATE_PROGRAM_WORKOUTS',
  ADD_PROGRAM_WORKOUT: 'ADD_PROGRAM_WORKOUT',
  DELETE_PROGRAM_WORKOUT: 'DELETE_PROGRAM_WORKOUT',
  ADD_CURRENT_PROGRAM_WORKOUT: 'ADD_CURRENT_PROGRAM_WORKOUT',
  SET_CURRENT_PROGRAM_WORKOUT: 'SET_CURRENT_PROGRAM_WORKOUT',
  CLEAR_CURRENT_PROGRAM_WORKOUT: 'CLEAR_CURRENT_PROGRAM_WORKOUT',
  CLEAR_CURRENT_PROGRAM_WORKOUTS: 'CLEAR_CURRENT_PROGRAM_WORKOUTS',
  SET_PROGRAM_WORKOUTS_ERROR: 'SET_PROGRAM_WORKOUTS_ERROR',
  FETCH_NEXT_PROGRAM_WORKOUT: 'FETCH_NEXT_PROGRAM_WORKOUT',
  SET_NEXT_PROGRAM_WORKOUT: 'SET_NEXT_PROGRAM_WORKOUT',
  CLEAR_NEXT_PROGRAM_WORKOUT: 'CLEAR_NEXT_PROGRAM_WORKOUT',
  RESET_PROGRAM_WORKOUTS: 'RESET_PROGRAM_WORKOUTS',
};

export default types;
