const types = {
  FETCH_PROGRAM_WORKOUTS: 'FETCH_PROGRAM_WORKOUTS',
  SET_PROGRAM_WORKOUTS: 'SET_PROGRAM_WORKOUTS',
  CLEAR_CURRENT_PROGRAM_WORKOUTS: 'CLEAR_CURRENT_PROGRAM_WORKOUTS',
  UPDATE_PROGRAM_WORKOUTS: 'UPDATE_PROGRAM_WORKOUTS',
  ADD_CURRENT_PROGRAM_WORKOUT: 'ADD_CURRENT_PROGRAM_WORKOUT',
  SET_CURRENT_PROGRAM_WORKOUT: 'SET_CURRENT_PROGRAM_WORKOUT',
  CLEAR_CURRENT_PROGRAM_WORKOUT: 'CLEAR_CURRENT_PROGRAM_WORKOUT',
  SET_PROGRAM_WORKOUTS_ERROR: 'SET_PROGRAM_WORKOUTS_ERROR',
};

export default types;
